Debugged minor bugs and improved error handling.

diff --git a/neurobionics-netcli/neurobionics-netcli b/neurobionics-netcli/neurobionics-netcli
--- a/neurobionics-netcli/neurobionics-netcli
+++ b/neurobionics-netcli/neurobionics-netcli
@@ -5,15 +5,17 @@ if [ "$(id -u)" != "0" ]; then
    exit 1
 fi
 
-# Comment this out if you want to log every boot cycle
-echo "neurobionics-netcli: $(date)" | tee /etc/neurobionics-netcli.log
+echo "=================================================" | tee -a /etc/neurobionics-netcli.log
+echo "neurobionics-netcli: $(date)" | tee -a /etc/neurobionics-netcli.log
 
 # Variables for connectivity routine
 
 wifi=wlan0
-ethernet=eth0
-timeout=60
+ssid="MWireless"
+
 networkconf="/etc/systemd/network/08-${wifi}-CLI.network"
+conf_file="/etc/wpa_supplicant/wpa_supplicant-wlan0.conf"
+temp_file="${conf_file}.tmp"
 
 # Email count file
 COUNT_FILE="/etc/neurobionics-netcli.count"
@@ -25,22 +27,86 @@ else
     SUCCESS_COUNT=0
 fi
 
+is_ap () {
+    # use wpa_cli to find if the current mode is AP
+    if [ -e $networkconf~ ]; then
+        echo "is_ap: True" | tee -a /etc/neurobionics-netcli.log
+        return 0
+    else
+        echo "is_ap: False" | tee -a /etc/neurobionics-netcli.log
+        return 1
+    fi
+}
+
+is_wpa_ap() {
+    if wpa_cli -i $wifi status | grep -q "mode=AP"; then
+        echo "is_wpa_cli_ap: True" | tee -a /etc/neurobionics-netcli.log
+        return 0
+    else
+        echo "is_wpa_cli_ap: False" | tee -a /etc/neurobionics-netcli.log
+        return 1
+    fi
+}
+
+is_client () {
+    # use wpa_cli to find if the current mode is client
+    if [ -e $networkconf ]; then
+        echo "is_client: True" | tee -a /etc/neurobionics-netcli.log
+        return 0
+    else
+        echo "is_client: False" | tee -a /etc/neurobionics-netcli.log
+        return 1
+    fi
+}
+
+is_wpa_client() {
+    if wpa_cli -i $wifi status | grep -q "mode=station"; then
+        echo "is_wpa_client: True" | tee -a /etc/neurobionics-netcli.log
+        return 0
+    else
+        echo "is_wpa_client: False" | tee -a /etc/neurobionics-netcli.log
+        return 1
+    fi
+}
+
 # Functions for connectivity routine, read more at https://raspberrypi.stackexchange.com/questions/100195
 # Configuring Access Point (AP) mode
 
 configure_ap () {
-    if [ -e $networkconf ]; then
+    # only configure AP if not already in AP mode
+    if is_wpa_client && is_client; then
+        echo "Removing client network configuration and restarting networkd" | tee -a /etc/neurobionics-netcli.log
         mv $networkconf $networkconf~
         systemctl restart systemd-networkd
+    elif is_client; then
+        echo "Client network configuration exists but wpa_cli is not in client mode. Removing client network configuration and restarting networkd." | tee -a /etc/neurobionics-netcli.log
+        mv $networkconf $networkconf~
+        systemctl restart systemd-networkd
+    elif is_wpa_client; then
+        echo "Client network configuration is missing but wpa_cli is in client mode. Restarting wpa_supplicant." | tee -a /etc/neurobionics-netcli.log
+        systemctl restart systemd-networkd        
+    else
+        echo "AP mode is already active. Skipping configuration." | tee -a /etc/neurobionics-netcli.log
     fi
 }
 
 # Configuring Client (CLI) mode
 
 configure_client () {
-    if [ -e $networkconf~ ] && wpa_cli -i $wifi status | grep -q "mode=station"; then
+    # only configure client if not already in client mode
+    if is_wpa_ap && is_ap; then
+        echo "Removing AP network configuration and restarting networkd" | tee -a /etc/neurobionics-netcli.log
         mv $networkconf~ $networkconf
         systemctl restart systemd-networkd
+    elif is_ap; then
+        echo "AP network configuration exists but wpa_cli is not in AP mode. Removing AP network configuration and restarting networkd." | tee -a /etc/neurobionics-netcli.log
+        mv $networkconf~ $networkconf
+        systemctl restart systemd-networkd
+    elif is_wpa_ap; then
+        echo "AP network configuration is missing but wpa_cli is in AP mode. Restarting wpa_supplicant." | tee -a /etc/neurobionics-netcli.log
+        systemctl restart systemd-networkd
+    else
+        echo "Client mode is already active. Skipping configuration." | tee -a /etc/neurobionics-netcli.log
     fi
 }
 
@@ -48,18 +114,19 @@ configure_client () {
 
 reconfigure_wpa_supplicant () {
     sleep "$1"
-    systemctl restart systemd-networkd
     wpa_cli -i $wifi reconfigure
 }
 
 # Function to find and update the BSSID in the configuration file
 
 update_bssid() {
-    if grep -q "ssid=\"MWireless\"" /etc/wpa_supplicant/wpa_supplicant-wlan0.conf; then
-        echo "MWireless network block found in the configuration file." | tee -a /etc/neurobionics-netcli.log
+    # Check if the SSID exists in the configuration
+    if grep -q "ssid=\"$ssid\"" "$conf_file"; then
+        echo "$ssid network block found in the configuration file." | tee -a /etc/neurobionics-netcli.log
 
         # Perform a fresh scan to get all available BSSIDs
         wpa_cli -i wlan0 scan
+        sleep 1
         echo "Scanning for available networks..." | tee -a /etc/neurobionics-netcli.log
 
         # Find the BSSID with the strongest signal
@@ -84,6 +151,7 @@ update_bssid() {
             if [ "$original_bssid" != "$best_bssid" ]; then
                 echo "Updated BSSID differs from the original. Network restart required." | tee -a /etc/neurobionics-netcli.log
                 reconfigure_wpa_supplicant 1
+                exit 0
             fi
         else
             # Add the BSSID tag to the configuration file
@@ -93,11 +161,11 @@ update_bssid() {
             echo "Restarting the networking now!" | tee -a /etc/neurobionics-netcli.log
             # restart the network because we want the best bssid network block to be active
             reconfigure_wpa_supplicant 1
+            exit 0
         fi
     else
-        echo "MWireless network block not found in the configuration file. Skipping BSSID update." | tee -a /etc/neurobionics-netcli.log
+        echo "$ssid network block not found in the configuration file. Skipping BSSID update." | tee -a /etc/neurobionics-netcli.log
     fi
-
 }
 
 # Manual execution via command line arguments
@@ -123,21 +191,17 @@ case "$1" in
         ;;
 
     --start-ap)
-        wpa_cli -i $wifi select_network 0
         configure_ap
         exit 0
         ;;
 
     --stop-ap)
-        if [ -e $networkconf~ ]; then
-            mv $networkconf~ $networkconf
-            systemctl restart systemd-networkd
-            wpa_cli -i $wifi reconfigure
-        fi
+        configure_client
         exit 0
         ;;
 
     --select-network)
+        configure_client
         wpa_cli -i $wifi select_network $2
         exit 0
         ;;
@@ -165,6 +229,16 @@ case "$1" in
         exit 0
         ;;
 
+    --is-ap)
+        is_ap
+        exit 0
+        ;;
+
+    --is-client)
+        is_client
+        exit 0
+        ;;
+
     --send-ip)
         python /etc/startup_mailer.py
         exit 0
@@ -183,17 +257,6 @@ case "$1" in
 
 esac
 
-# Checking for Ethernet connection, if so the RPi behaves like a Wifi router
-
-if [ "$(cat /sys/class/net/${ethernet}/carrier)" = "1" ]; then
-    echo "Ethernet connection found, enabling Access Point (AP)." | tee -a /etc/neurobionics-netcli.log
-    if wpa_cli -i $wifi status | grep -q "mode=station"; then
-        wpa_cli -i $wifi select_network 0
-        configure_ap
-    fi	
-    exit 0
-fi
-
 # Automated execution based on wpa_supplicant activity
 
 case "$2" in
@@ -204,33 +267,36 @@ case "$2" in
 
     CONNECTED)
         configure_client
-        update_bssid
-        
-        max_attempts=10
-        attempt=1
 
-        while [ $attempt -le $max_attempts ]; do
-            python /etc/startup_mailer.py
-            if [ $? -eq 0 ]; then
-                echo "A login ticket was emailed successfully." | tee -a /etc/neurobionics-netcli.log
+        if is_wpa_client; then
+            echo "Client mode is active so we will update the BSSID." | tee -a /etc/neurobionics-netcli.log
+            update_bssid
+            
+            max_attempts=10
+            attempt=1
 
-                ((SUCCESS_COUNT++))
+            while [ $attempt -le $max_attempts ]; do
+                python /etc/startup_mailer.py
+                if [ $? -eq 0 ]; then
+                    echo "A login ticket was emailed successfully." | tee -a /etc/neurobionics-netcli.log
 
-                echo "SUCCESS: CLI MODE ON" | tee /etc/neurobionics-netcli.log
-                echo $SUCCESS_COUNT > $COUNT_FILE
-                break
-            else
-                echo "Python script failed. Retrying in a second." | tee -a /etc/neurobionics-netcli.log
-                sleep 1
-                attempt=$((attempt + 1))
-            fi
-        done
+                    ((SUCCESS_COUNT++))
 
-        if [ $attempt -gt $max_attempts ]; then
-			echo "Switching to AP mode" | tee -a /etc/neurobionics-netcli.log
-            echo "FAIL: AP MODE ON" | tee -a /etc/neurobionics-netcli.log
-			wpa_cli -i $wifi select_network 0
-			configure_ap
+                    echo "SUCCESS: CLI MODE ON" | tee -a /etc/neurobionics-netcli.log
+                    echo $SUCCESS_COUNT > $COUNT_FILE
+                    break
+                else
+                    echo "Python script failed. Retrying in a second." | tee -a /etc/neurobionics-netcli.log
+                    sleep 1
+                    attempt=$((attempt + 1))
+                fi
+            done
+
+            if [ $attempt -gt $max_attempts ]; then
+                echo "Switching to AP mode" | tee -a /etc/neurobionics-netcli.log
+                echo "FAIL: AP MODE ON" | tee -a /etc/neurobionics-netcli.log
+                configure_ap
+            fi            
         fi
         ;;
 
