Added 'remove-email' command to neurobionics-cli, fixes #8.

diff --git a/neurobionicspi-cli/neurobionicspi-cli b/neurobionicspi-cli/neurobionicspi-cli
--- a/neurobionicspi-cli/neurobionicspi-cli
+++ b/neurobionicspi-cli/neurobionicspi-cli
@@ -242,10 +242,33 @@ case "$1" in
             echo "No email address provided. Please provide an email address as an argument."
             exit 1
         fi
+
         email=$2
+
+        if grep -q "${email}" /etc/startup_mailer.py; then
+            echo "Email address is already present."
+            exit 0
+        fi
+
         sed -i "s/\(recipient_str = \"\)\([^\"]*\)\"/\1\2, ${email}\"/" /etc/startup_mailer.py
         echo "Email address added successfully."
         exit 0
+        ;;
+
+    --remove-email)
+        if [ -z "$2" ]; then
+            echo "No email address provided. Please provide an email address as an argument."
+            exit 1
+        fi
+        email=$2
+        if grep -q "${email}" /etc/startup_mailer.py; then
+            echo "Email address is present, proceeding to remove it."
+            sed -i "s/\(recipient_str = \".*\)\(${email}, \|, ${email}\)\(.*\"\)/\1\3/" /etc/startup_mailer.py
+            echo "Email address removed successfully."
+            exit 0
+        fi
+
+        echo "Email address not found."
         ;;
 
 esac
