Added another condition.

diff --git a/neurobionicspi-cli/neurobionicspi-cli b/neurobionicspi-cli/neurobionicspi-cli
--- a/neurobionicspi-cli/neurobionicspi-cli
+++ b/neurobionicspi-cli/neurobionicspi-cli
@@ -85,8 +85,23 @@ configure_ap () {
 
         echo "Restarting networkd." | tee -a /etc/neurobionicspi-cli.log
         systemctl restart systemd-networkd
+
+    elif is_wpa_ap; then
+        if ! is_ap_conf; then
+            echo "AP network configuration is missing. Creating AP network configuration." | tee -a /etc/neurobionicspi-cli.log
+            mv $apconf~ $apconf
+        fi
+
+        if is_client_conf; then
+            echo "Both AP and client network configurations exist. Removing client configuration and restarting networkd." | tee -a /etc/neurobionicspi-cli.log
+            mv $networkconf $networkconf~
+        fi
+
+        echo "In AP mode but not configured as such. Restarting networkd." | tee -a /etc/neurobionicspi-cli.log
+        systemctl restart systemd-networkd
+
     else
-        echo "Already in AP mode. Skipping configuration." | tee -a /etc/neurobionicspi-cli.log
+        echo "Something went wrong. Neither AP nor client mode is active." | tee -a /etc/neurobionicspi-cli.log
     fi
 }
 
@@ -106,8 +121,23 @@ configure_client () {
 
         echo "Restarting networkd." | tee -a /etc/neurobionicspi-cli.log
         systemctl restart systemd-networkd
+
+    elif is_wpa_client; then
+        if ! is_client_conf; then
+            echo "Client network configuration is missing. Creating client network configuration." | tee -a /etc/neurobionicspi-cli.log
+            mv $networkconf~ $networkconf
+        fi
+
+        if is_ap_conf; then
+            echo "Both AP and client network configurations exist. Removing AP configuration and restarting networkd." | tee -a /etc/neurobionicspi-cli.log
+            mv $apconf $apconf~
+        fi
+
+        echo "In client mode but not configured as such. Restarting networkd." | tee -a /etc/neurobionicspi-cli.log
+        systemctl restart systemd-networkd
+
     else
-        echo "Already in client mode. Skipping configuration." | tee -a /etc/neurobionicspi-cli.log
+        echo "Something went wrong. Neither AP nor client mode is active." | tee -a /etc/neurobionicspi-cli.log
     fi
 
 }
